site_name: mekd
site_author: Gavin Gao
site_url: https://mekd.cgabc.xyz/
site_description: Maths, Estimation, Kinematics and Dynamics

repo_url: https://github.com/cggos/mekd
repo_name: cggos/mekd

theme: 
  name: material # readthedocs material
  # logo: material/library
  favicon: images/favicon.png
  icon:
    repo: fontawesome/brands/git-alt
  nav_style: light
  language: 'zh'
  # palette:
  #   primary: 'light blue'
  #   accent: 'indigo' 
  feature:
    tabs: true
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.prune
    - navigation.indexes
    - navigation.top
    - toc.follow
    # - toc.integrate
    - content.code.annotate

plugins:
  - search
  # - social
  - tags

markdown_extensions:
  - abbr
  - meta
  - admonition
  - attr_list
  - def_list
  - footnotes
  - toc:
      permalink: true # "#"
      toc_depth: 5
      separator: "_"
      slugify: !!python/name:pymdownx.slugs.uslugify_cased
  - codehilite:
      guess_lang: true
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.arithmatex
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.magiclink
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde        
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.highlight:
      auto_title: true
      anchor_linenums: true
      linenums_style: pymdownx-inline
  - pymdownx.tabbed:
      alternate_style: true       
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      # emoji_generator: !!python/name:pymdownx.emoji.to_png
  - pymdownx.tasklist:
      custom_checkbox: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/cggos
      name: cggos on GitHub
    - icon: fontawesome/brands/twitter 
      link: https://x.com/GavnGao
      name: CGABC on X


nav:
  - Home: index.md

  - Maths:
    - Overview: maths/README.md

    - C++:
      - Eigen: maths/cpp/eigen.md
      - Maths Libs: maths/cpp/math_libs.md

    - Python:
      - Overview: maths/python/README.md
      - Anaconda: maths/python/anaconda.md
      - pip & Wheel: maths/python/pip_whl.md
      - Libs: maths/python/py_libs.md

    - Matlab:
      - Overview: maths/matlab/README.md

    - R: maths/r/README.md

    - Wolfram:
      - Overview: maths/wolfram/README.md
      - Wolfram Mathematica: maths/wolfram/wolfram_mathematica.md

    - Math Typesetting:
      - Overview: maths/typesetting/README.md
      - Conda: maths/typesetting/conda.md
      - Jupyter: maths/typesetting/jupyter.md
      - TeX: maths/typesetting/TeX.md

    - Appendix:
      - Overview: maths/appendix/README.md

  - Estimation:
    - Overview: estimation/README.md
    - Filter: estimation/filter/README.md
    - MAP: estimation/map/README.md
    - Solver: estimation/solvers/README.md

  - Kinematics & Dynamics:
    - Overview: kd/README.md